[project]
name = "spicy-qc"
version = "0.1.0"
description = "Granular quality control system with clear visual feedback, designed to help teams quickly identify, understand, and resolve issues during production"
readme = "README.md"
authors = [
    { name = "Tristan Languebien", email = "tlanguebien@gmail.com" }
]
requires-python = ">=3.9"
dependencies = [
    "PySide6",
    "QtPy",
    "QtAwesome",
    "Markdown"
]

[project.scripts]
spicy-qc = "spicy_qc:main"

[build-system]
requires = ["uv_build>=0.10.11,<0.11.0"]
build-backend = "uv_build"
