# TUTORIAL
# Edit this file then run this command in the root directory
# uv sync --extra docs
# zensical serve
#
# The documentation can be seen by going on chrome :
# http://localhost:8000/

# ressources :
# https://gist.github.com/rxaviers/7360908

[project]
site_name = "SpicyQC"
site_description = "Quality Control system with clear visual feedback, designed to help teams quickly identify, understand, and resolve issues during production"
site_url = "https://bigcompany-public.github.io/spicy_qc/"
repo_url = "https://github.com/bigcompany-public/spicy_qc/"
repo_name = "bigcompany-public/spicy_qc"
edit_uri = "edit/main/docs/"
extra_css = ["stylesheets/extra.css"]
nav = [
    { "Home" = "index.md" },
    { "QuickStart" = "quickstart.md" },
    { "User Documentation" = "user_documentation.md" },
    { "TD/Dev Documentation" = "dev_documentation.md" },
    { "Markdown Reference" = "markdown.md" },
]

# Palette toggle for dark mode
[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "blue"
accent = "blue"
toggle.icon = "lucide/moon-star"
toggle.name = ""

[project.theme]
features = [
    "navigation.sections",
    "navigation.top",
    "search.suggest",
    "search.highlight",
    "content.tabs.link",
    "content.code.annotation",
    "content.code.copy",
]

[project.theme.icon]
repo = "fontawesome/brands/github"
